# -*- coding: utf-8 -*-
"""ASSIGNMENT : 6	.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vl6OIwpfckP8g41vVrb2hntPkwJm84HQ

ASSIGNMENT : 6

Application of Python in the field of Soil Mechanics
"""

print("Name: Saurabh Shyam Gayke ; Class and Division: BE-A ; Batch : C ; Roll No 21CV313")

# Calculating the stress by Boussineq's Theory
Q= int(input("Enter the value of given load :"))
z= int(input("Enter the distance of vertical stress :"))
r= int(input("Enter the distance ofhorizntal stress:"))
stress = ((3*Q*(1/(1+(r/z)**2)) **2.5))/(2%3.14*(z**2))
print("The value of stress is", stress)